### ISSUE TITLE
Planning (Week1) - Sign up Could Servies and Install GUIs for RDB, MongoDB (output: account and user guideline)

### ISSUE THREAD

**Issue by Gs1TestTeam** [Gs1TestTeam/MongoDB_Task#3]
Q: Do we need to research about MongoDB compatible with IBM server?

**Comment by hirocsingh** [comment]
MongoDB is compatible with IBM Servers running POWER OS.

Find Information in the following link:
[https://developer.ibm.com/linuxonpower/2017/01/17/mongodb-3-4-now-available-for-new-platforms-including-power/](url)

**Comment by hirocsingh** [comment]
Account has been created on [mLab](https://mlab.com/) a Database-as-a-Service provider which gives the user option to choose between different cloud service providers such as Google, AWS and Azure. [mLab](https://mlab.com/) comes with pre-installed latest MongoDB and a GUI tool and Import/Export Tool for Data migration.

Steps to sign up on [mLab](https://mlab.com):
 - 1.  [Sign Up](https://mlab.com/signup/)

 - 2. Create a new MongoDB Deployment.
<img width="921" alt="mlab_01" src="https://user-images.githubusercontent.com/21228750/45097953-f80cde80-b0f1-11e8-8af4-bf934511088f.png">

 - 3.  Select Cloud provider and plan type for storage.
<img width="638" alt="mlab_02" src="https://user-images.githubusercontent.com/21228750/45097742-82a10e00-b0f1-11e8-88ac-c6b1c47f6fb3.png">

 - 4. Choose you server region.
<img width="237" alt="mlab07" src="https://user-images.githubusercontent.com/21228750/45097852-c431b900-b0f1-11e8-80b4-b0490ee71b5e.png">

 - 5. Choose the newly create server and Create a Database.
 <img width="894" alt="mlab04" src="https://user-images.githubusercontent.com/21228750/45098246-95681280-b0f2-11e8-9d81-033fdbd8854d.png">
 <img width="871" alt="mlab_03" src="https://user-images.githubusercontent.com/21228750/45098323-bc264900-b0f2-11e8-89d0-f31be03e15e3.png">

 - 6. Use the following command to connect to the server.
  <img width="553" alt="mlab09" src="https://user-images.githubusercontent.com/21228750/45098568-41a9f900-b0f3-11e8-9782-00277994dc10.png">

**Comment by hirocsingh** [comment]
We can use GUI of our choice, I have posted list of popular MongoDB GUI tools under [GUI Application](https://github.com/Gs1TestTeam/MongoDB_Task/wiki/1-2.-GUI-Application) wiki of this Project.

Alternatively you can use mLab's embedded GUI to INSERT, DELETE, UPDATE....on the collection.
